"""
GitHub PR Comment integration for DeepSentinel.
Posts security findings directly as PR comments — actionable where developers already work.
This is what makes DeepSentinel immediately useful: findings appear IN the PR, not in a dashboard.
"""
import os
import httpx


async def post_pr_comment(owner: str, repo: str, pr_number: int,
                          findings: list, correlations: list,
                          token: str = None) -> bool:
    """
    Post a formatted security review comment on a GitHub PR.
    This is the "immediately useful" feature — developers see findings
    right where they're reviewing code.
    """
    token = token or os.environ.get("GITHUB_TOKEN", "")
    if not token:
        print("[GitHub] No token — skipping PR comment")
        return False

    comment = _format_pr_comment(findings, correlations)

    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments",
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github.v3+json",
            },
            json={"body": comment},
        )
        if resp.status_code == 201:
            print(f"[GitHub] Security review posted on PR #{pr_number}")
            return True
        else:
            print(f"[GitHub] Failed to post comment: {resp.status_code}")
            return False


def _format_pr_comment(findings: list, correlations: list) -> str:
    """Format findings as a GitHub PR comment with markdown."""
    severity_counts = {}
    for f in findings:
        sev = f.get("severity", "UNKNOWN").upper()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    critical = severity_counts.get("CRITICAL", 0)
    high = severity_counts.get("HIGH", 0)

    # Header with recommendation
    if critical > 0:
        recommendation = "BLOCK"
        emoji = "🔴"
    elif high > 0:
        recommendation = "REVIEW"
        emoji = "🟡"
    else:
        recommendation = "APPROVE"
        emoji = "🟢"

    lines = [
        f"## {emoji} DeepSentinel Security Review",
        "",
        f"**{len(findings)} findings** | {critical} critical | {high} high | Recommendation: **{recommendation}**",
        "",
    ]

    # Cross-source intelligence section
    if correlations:
        lines.append("### Cross-Source Intelligence")
        lines.append("")
        lines.append("> These findings come from correlating code changes with team discussions (GitHub Issues, PR comments). No single-source scanner can produce these insights.")
        lines.append("")
        for corr in correlations[:5]:
            risk = corr.get("risk_note", "")
            why = corr.get("why_code_only_misses", "")
            confidence = corr.get("confidence", "")
            lines.append(f"- **[{confidence}]** {risk}")
            if why:
                lines.append(f"  - *Why scanners miss this:* {why}")
        lines.append("")

    # Top findings
    lines.append("### Top Findings")
    lines.append("")
    for f in sorted(findings, key=lambda x: {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}.get(x.get("severity", "").upper(), 4))[:8]:
        sev = f.get("severity", "?").upper()
        cwe = f.get("cwe_id", "")
        title = f.get("title", "Unknown")
        file_path = f.get("file_path", "")
        line = f.get("line_number", "")
        fix = f.get("fix_suggestion", f.get("fix", ""))

        sev_emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵"}.get(sev, "⚪")
        lines.append(f"#### {sev_emoji} [{sev}] {title}")
        if cwe:
            lines.append(f"**{cwe}** | `{file_path}:{line}`")
        if fix:
            lines.append(f"> Fix: {fix[:200]}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [DeepSentinel](https://github.com/ElijahUmana/deep-sentinel) — cross-source security intelligence*")

    return "\n".join(lines)
